[phases.install]
cmds = ["npm install --no-cache"]

[phases.build]
cmds = [
  "npm run build --workspace=frontend",
  "npm run build --workspace=backend",
  "npm run postbuild"
]

[start]
cmd = "npm start"
